; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = libopencm3
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
upload_flags = -c set CPUTAPID 0x2ba01477
build_flags = -fno-use-cxa-atexit -mthumb -std=c++11 -mfpu=fpv4-sp-d16 -mfloat-abi=hard
lib_deps = FreeRTOS
board_build.mcu = stm32f411ceu6
board_build.f_cpu = 100000000L
upload_port = COM10
extra_scripts = post:link_hardfloat.py